### ISSUE TITLE
Lägg till sessionshantering i klienten

### ISSUE THREAD

**Issue by marja992** [uppsala-university/ati-ladok3-rest-client#2]
Vi behöver hålla sessioner i klienten för att slippa göra inloggningar vid varje anrop. Det behöver vi göra både för att att öka prestandan lokalt men också för att inte belästa nya Ladok med onödig last i form av väldigt många inloggningar. Initialt använder vi vanlig webbsession-hantering. Vid ett senare tillfälle har L3-projektet aviserat någon annan form av "sessionshantering".

**Comment by henrerik** [comment]
Jag har lagt till en global CookieManager som inkluderar alla cookies, inklusive vår sessions-cookie från Ladok. 

Notera att detta behöver göras lite mer finfördelat om vi i framtiden skulle behöva använda samma REST-klient för att hantera olika certifikat i samma applikation. Då skulle man behöva separera olika cookies t.ex. per tråd så de olika sessionerna inte blandas samman. Vare sig Selma-projektet eller UUs Studentportal har det behovet i nuläget.
